# Site Information
site_name: MeshMapper Wiki
site_url: https://meshmapper.net
site_description: Community-driven visualization and analytics platform for MeshCore LoRa mesh networks
edit_uri: ""

# Navigation Structure
nav:
  - Home: index.md
  
  - Getting Started:
    - Onboarding New Regions: onboarding.md
  
  - Using the Map:
    - Map Layers & Filters: layers.md
    - Understanding Visuals: visuals.md
    - Duplicate Repeater IDs: duplicaterepeaterid.md
    - Override Duplicate IDs: overrideduplicates.md
  
  - Community:
    - Leaderboards & Statistics: leaderboards.md
  
  - Administration:
    - Administrator List: administratorlist.md
    - Admin Portal: admins.md
    - Data Upload: dataupload.md
  
  - Support:
    - Report Bugs & Features: reportbugs.md

  - Release Notes:
    - February 12, 2026: release-notes/260212.md
    - February 9, 2026: release-notes/260209.md
    - February 7, 2026: release-notes/260207.md
    - February 5, 2026: release-notes/260205_2.md
    - February 5, 2026: release-notes/260205.md
    - February 4, 2026: release-notes/260204.md
    - February 3, 2026: release-notes/260203_2.md
    - February 3, 2026: release-notes/260203.md
    - January 31, 2026: release-notes/260131_2.md
    - January 31, 2026: release-notes/260131.md
    - January 30, 2026: release-notes/260130.md
    - January 29, 2026: release-notes/260129.md

# Theme Configuration
theme:
  name:  material
  logo: assets/wardrive.png
  favicon: assets/wardrive.png
  palette:
    scheme: slate

# Markdown Extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - macros
  - glightbox:
      touchNavigation: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
