# Site Information
site_name: MeshMapper Wiki
site_url: https://meshmapper.net
site_description: Community-driven visualization and analytics platform for MeshCore LoRa mesh networks
edit_uri: ""

# Navigation Structure
nav:
  - Home: index.md
  
  - Getting Started:
    - Onboarding New Regions: onboarding.md
  
  - Using the Map:
    - Map Layers & Filters: layers.md
    - Understanding Visuals: visuals.md
    - Duplicate Repeater IDs: duplicaterepeaterid.md
  
  - Community:
    - Leaderboards & Statistics: leaderboards.md
  
  - Administration:
    - Admin Portal: admins.md
  
  - Support:
    - Report Bugs & Features: reportbugs.md

# Theme Configuration
theme:
  name:  material
  logo: assets/wardrive.png
  favicon: assets/wardrive.png
  palette:
    scheme: slate

# Markdown Extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - macros
  - glightbox:
      touchNavigation: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
